# Generated by Django 4.0.5 on 2022-07-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BinaryField(primary_key=True, serialize=False, unique=True)),
                ('credential_id', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('sign_count', models.PositiveBigIntegerField()),
                ('transports', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
