# Generated by Django 4.0.5 on 2022-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_credential_useraccount_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BinaryField(primary_key=True, serialize=False)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
