# Generated by Django 4.0.5 on 2022-07-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_delete_user_usercredential_credential_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='user',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
