# Generated by Django 4.0.5 on 2022-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usercredential_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='credential_id',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='public_key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BinaryField(primary_key=True, serialize=False, unique=True),
        ),
    ]
