# Generated by Django 4.0.5 on 2022-07-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
