# Generated by Django 4.0.5 on 2022-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='id',
            field=models.BinaryField(primary_key=True, serialize=False, unique=True),
        ),
    ]
