# Generated by Django 4.0.5 on 2022-09-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredential',
            old_name='username',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credentials',
        ),
    ]
